### PR TITLE
Upgrade To Rails

### PR DESCRIPTION
**Pull request by Skipper-116**
## Description
This is where all the work to upgrade the rails App will be taking place

```DO NOT MERGE WITHOUT GOING THROUGH RIGOROUS TESTING``` @pamzey ```PLEASE GO TRHOUGH THE CODE AND THE DIFFERENT WORKFLOWS BEFORE APPROVING OR MERGING THIS WORK```

### CODE REVIEW

**Review by pamzey — APPROVED** [review]
Well noted

**Comment by Skipper-116** [comment]
@pamzey please go through the changes before you rebase

**Comment by pamzey** [comment]
Sure i will check and test these changes

**Comment by pamzey** [comment]
I have tested and the api is running OK on Rails 7.0.8 and Ruby 3.2.0

**Pull request merged**
